name: ProtectionGems
version: 1.0
main: me.demonducky.protectiongems.ProtectionGems
api-version: 1.20
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.10'
commands:
  protectiongems:
    description: Quản lý Ngọc Bảo Vệ
    usage: /<command> give <player> <amount>
    permission: protectiongems.use
permissions:
  protectiongems.use:
    description: Cho phép sử dụng lệnh protectiongem
    default: op